### ISSUE TITLE
TypeError: setRange(self, int, int): argument 2 has unexpected type 'float' 

### ISSUE THREAD

**Issue by husnejahan** [All4Gis/QGISFMV#122]
Hi 

I have installed the QGISFMV plugin, but when trying to play .ts video file I am getting an error as follows:

An error has occurred while executing Python code: 

Traceback (most recent call last):
  File "/home/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QGIS_FMV/manager/QgsManager.py", line 372, in PlayVideoFromManager
    self.CreatePlayer(path, self.update_interval, model.row(), islocal=True, klv_folder=klv_folder)
  File "/home/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QGIS_FMV/manager/QgsManager.py", line 413, in CreatePlayer
    self._PlayerDlg = QgsFmvPlayer(self.iface, path, interval, parent=self, meta_reader=self.meta_reader[
  File "/home/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QGIS_FMV/player/QgsFmvPlayer.py", line 167, in __init__
    self.sliderDuration.setRange(0, self.player.duration() / 1000)
TypeError: setRange(self, int, int): argument 2 has unexpected type 'float'

---------------------------------------------------------------------------------------------
Python version: 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] 
QGIS version: 3.26.0-Buenos Aires Buenos Aires, 0aece2818e

**Comment by All4Gis** [comment]
mmm.. strange, can you share the video you are testing?

**Comment by husnejahan** [comment]
Hi,
I have used the example video from the following link:

https://www.arcgis.com/home/item.html?id=55ec6f32d5e342fcbfba376ca2cc409a

**Comment by All4Gis** [comment]
Strange, that's the video I use to test the functionality and develop it. Anyway here you have videos to test it
https://drive.google.com/drive/folders/1-B2uaW7_cfYZohZYFozrgBhIaztI1MSP

**Comment by husnejahan** [comment]
Hi 

I have tried other ts file too. The same issue. 

I re-installed the QGISFMV plugin again from zip file
https://github.com/All4Gis/QGISFMV.git.

Also have installed QGIS from the following instruction:

https://www.youtube.com/watch?v=YVE_gXPaMsU
