### ISSUE TITLE
Plugin not working[BUG]

### ISSUE THREAD

**Issue by jonititan** [All4Gis/QGISFMV#123]
**Describe the bug**
Slider gets passed floats occasionally which causes failure.

Also depreciation warnings.

Cannot get the processed data to display on the map.
https://youtu.be/PiUr6wyY_M4

**To Reproduce**
Play a compatible video and see metadata extracted and plotted.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 22
 - QGIS Version 3.22
 - Plugin Version 1.15

**Additional context**

**Comment by All4Gis** [comment]
Hi @jonititan  the video you are using only has metadata in the second zero. I used another example idea, but that one just doesn't have the god telemetry

**Comment by jonititan** [comment]
Ah that would explain it.
For documentation purposes I was using the test video from https://github.com/tayre/klv-decoder
I'll try to find another test video

**Comment by All4Gis** [comment]
check this folder https://drive.google.com/drive/folders/1-B2uaW7_cfYZohZYFozrgBhIaztI1MSP

**Comment by jonititan** [comment]
Thanks I will

**Comment by jonititan** [comment]
Just tried one of those.  Yes it works correctly now I'll close this.
Still some warnings and trajectory not being updated but I will document those more carefully and see if I can fix and raise a PR to merge later.

Thank you
