### ISSUE TITLE
Video Working but path and Footprint are not displayed 

### ISSUE THREAD

**Issue by Eandelin** [All4Gis/QGISFMV#18]
Can play the sample videos, but does not plot flight path or footprint.  Log file error below. 

2018-08-07T18:08:52     WARNING    CreatePlotsBitrate : Failed! CreatePlotsBitrate.error[str, Exception, str].emit(): argument 2 has unexpected type 'str'

**Comment by All4Gis** [comment]
Hi
what video are you using?this error is when you show the bitrate,but footprint and flight path is other way.

**Comment by Eandelin** [comment]
Video used was your sample Cheyenne.ts

**Comment by All4Gis** [comment]
mmmm...is so strange then!if open qgis,next open video not show trajectory?this video work perfectly

**Comment by All4Gis** [comment]
okey!install prerequisites again a restart qgis!Are you using QGIS 3?have correct FFMPEG path in fmvconfig.py ?Cheack again

**Comment by Eandelin** [comment]
QGIS Version 3.2

**Comment by All4Gis** [comment]
use double slash in ffmpeg and ffprobe paths!in this folder you have this?

matlab?

![sin titulo](https://user-images.githubusercontent.com/8123225/43853906-bd1abc68-9b41-11e8-9fa9-89cd1f5d860c.png)

**Comment by Eandelin** [comment]
Yeah I'm lost . It  has to be the install/placement/location/modification of all these additional files.

**Comment by Eandelin** [comment]
![lost](https://user-images.githubusercontent.com/42190209/43917413-47e72a06-9bde-11e8-9cca-f74fe4e7ee74.PNG)

**Comment by All4Gis** [comment]
About this message you need install open cv and put the correct path for ffmpeg

Use my capture for replicate the paths

**Comment by All4Gis** [comment]
no! you need install requiremets file using **python3 -m pip install -r requirements.txt** and FFMPEG in any directory,and change the fmvconfig.py!Yesterday i will make for a complet installation on windows,all steps

**Comment by Eandelin** [comment]
I'll give it a try in the morning. Forgive my poor programming skills. Way
to dependent on Windows...Glad your going to make a Windows install.

**Comment by All4Gis** [comment]
Dowload the new available versio 1.2 from QGIS plugins manger!because i wil make a tutorial for this version

**Comment by All4Gis** [comment]
check this video https://www.youtube.com/watch?v=9C973pz5i6k&feature=youtu.be is spanish but the steps is so simpe!

**Comment by Eandelin** [comment]
me dará la oportunidad de practicar mi español

**Comment by Eandelin** [comment]
Not yet. I've tried but failed so far. A couple of questions. 

 I downloaded and extracted the install zip file (QGISFMY-master) into my downloads folder  same as 1:49 in video

1.) Does this contain the dependencies as well? 

2.) If I have only installed QGIS using the standalone installer into this folder. C:\Program Files\QGIS 3.2
![capture1](https://user-images.githubusercontent.com/42190209/44533342-53d37280-a6c3-11e8-9077-e1f550a0c25e.PNG)

Then I should use this path in the py3-env.bat file as 4:08 in the video...and change nothing else? 

![capture2](https://user-images.githubusercontent.com/42190209/44533597-e247f400-a6c3-11e8-92e3-21ef3880f6bd.PNG)

If I run the install-pip_packages.bat. I can confirm the packages have been installed, but there appears to be errors.
![capture3](https://user-images.githubusercontent.com/42190209/44534223-4323fc00-a6c5-11e8-9cb6-0f90f4337d8b.PNG)

I installed LAV Filter no issues. 

I installed FFMPEG in the same folder as video @ 7;18 C:\QgisFFMPEG
![capture4](https://user-images.githubusercontent.com/42190209/44534649-48357b00-a6c6-11e8-8e2b-15e79becfa87.PNG)

**It appears your download folder @ 7:25 in the video is missing two files: avcodec-58.dll and ffmpeg. This might be the problem. Please check your win folder on your google drive.**

**Comment by All4Gis** [comment]
**1.)Does this contain the dependencies as well?**

this is oly the plugin and install any dependencies but you need install manually

**2.) Then I should use this path in the py3-env.bat file as 4:08 in the video...and change nothing else?**

yes only this but not use space in this path,use "C:\PROGRA~1\QGIS3~1.2"

When run install-pip_packages.bat,lose QGIS before and run this .bat with administrative privileges
 
mm..the drive folder have all .dll but not worries,you can dowload the files from offical site 
https://www.ffmpeg.org/download.html#build-windows

**Comment by Eandelin** [comment]
I downloaded them. Did not change the path. this was copied directly from the folder. It seems to be working:-).  I want to try it on one of my files but they are mp4. I'll have to convert and hope it does not strip the MISB info.

**Comment by All4Gis** [comment]
Good news then.
Is your file confidential? The plugin should be able to work with .mp4 file!
Can you share it with me to do tests?

**Comment by All4Gis** [comment]
Close the issue if you think it has been resolved

**Comment by Eandelin** [comment]
A link to samples was sent via LinkedIn messages.  I have not been able to get them working in your plugin. I created the Metadata extraction routine (what was publicly available was not good).The sample files were multiplexed in ESRI and work fine in the ArcGIS.  Hoping to find a way to multiplex without ESRI.

**Comment by All4Gis** [comment]
Thanks!In some higher version the tool to multiplex videos will be integrated
