### ISSUE TITLE
Qgis crash

### ISSUE THREAD

**Issue by kikislater** [All4Gis/QGISFMV#19]
Launching from terminal, then activate plugin crash qgis : 

```
QGIS died on signal 11ptrace: Operation not permitted.
No thread selected
No stack.
gdb returned 0
Aborted (core dumped)
```

OS = Manjaro Linux 64

> $ pacman -Q qgis
> qgis 3.2.0-2

> $ pacman -Q python-matplotlib
> python-matplotlib 2.2.2-2

> pip list | grep opencv
> opencv-python                3.3.0.10

> pip list | grep homography
> homography                   0.1.5

> $ which ffmpeg
> /usr/bin/ffmpeg

> $ cat fmvConfig.py 
> # **********    Properties    **********
> 
> # Layer names
> Platform_lyr = "Platform"
> Beams_lyr = "Beams"
> Footprint_lyr = "Footprint"
> Trajectory_lyr = "Trajectory"
> Point_lyr = "Drawings"
> 
> # Group Name
> frames_g = "FMV Georeferenced Frames"
> 
> # FFmpeg path
> ffmpeg = "/usr/bin/ffmpeg"
> ffprobe = "/usr/bin/ffprobe"

![capture du 2018-08-08 18-17-08](https://user-images.githubusercontent.com/13238064/43843354-6959f6ec-9b38-11e8-94b2-181749aa1c8c.png)

Edit : upgraded to opencv-python-3.4.0.12 and still crash

**Comment by All4Gis** [comment]
can you open qgis without plugin?that is a mistake of qgis, not the plugin

**Comment by kikislater** [comment]
Yes of course, I use it every day ...
How to debug it ? I use others plugins, this one is the only one making qgis crashing !

**Comment by All4Gis** [comment]
I will try to reproduce it in the same version of OS that you

**Comment by kikislater** [comment]
There is another version in testing repository. I will test it tomorrow and on another installation.

**Comment by kikislater** [comment]
Ok it works on another installation. It seems to be opencv. I will tell you when I will find

**Comment by All4Gis** [comment]
I'm glad ! Could you send me a PR, to add your installation notes for this OS? So we add it to the readme so that other users don't have problems in the future.Thanks

**Comment by kikislater** [comment]
Yes ! Let me find the problem first. I'm on this second setup today. May be at the end of the day ...
I'm also interested in this plugin and curious about how you will compute footprint, is this implemented at this time ? I use an adjusted process from postgis cookbook to do it : https://github.com/giscan/Postgis-footprint

**Comment by All4Gis** [comment]
the methos are [CornerEstimationWithOffsets](https://github.com/All4Gis/QGISFMV/blob/master/code/utils/QgsFmvUtils.py#L997) and [CornerEstimationWithoutOffsets](https://github.com/All4Gis/QGISFMV/blob/master/code/utils/QgsFmvUtils.py#L1037)

**Comment by kikislater** [comment]
Hum seems perfect ! I think I will use your plugin.
Mind you use auto srtm download ? there is a python lib to do it : 30m worldwide => http://elevation.bopen.eu/en/stable/quickstart.html

**Comment by All4Gis** [comment]
this is nice! I didn't know that library! Could you make your changes in the code and send me PR?

**Comment by kikislater** [comment]
Yes but not for next day. When I will have more time ;-)

**Comment by All4Gis** [comment]
No worries!take your time!thanks

**Comment by kikislater** [comment]
Ok so just removing opencv installed from pip work and prevent qgis crashing. OpenCV package distribution already include python wrapper, so I think pip package and archlinux package are in conflict.
Where do I put PR ? How to edit readthedocs ? 

# Archlinux installation : 
# pacman -S qgis python-matplotlib opencv ffmpeg 
# pip install homography

# FFmpeg path
ffmpeg = "/usr/bin/"
ffprobe = "/usr/bin/"

**Comment by All4Gis** [comment]
Ah okey!change the readme.md!for example create a new block "installation notes". Use any text editor

**Comment by kikislater** [comment]
Hum, no ! I have updated to qgis 3.2.2 and now it install opencv version automatically in local pip repository I think. But for others things, it's ok !

**Comment by All4Gis** [comment]
ok! then close if your consider solved
