### ISSUE TITLE
Consider use elevation python library for download srtm data.

### ISSUE THREAD

**Issue by All4Gis** [All4Gis/QGISFMV#20]
http://elevation.bopen.eu/en/stable/quickstart.html

we'll wait to see if this is resolved
https://github.com/bopen/elevation/issues/11

**Comment by All4Gis** [comment]
It is not going to be implemented

**Comment by kikislater** [comment]
Could I ask why?

**Comment by All4Gis** [comment]
The problem is that you should go through the full video and not just a part (buffer cache) to get the complete trajectory and extract the correct bounding box.

This brings a lot of memory

If you do it only with the start / end it would not download a correct dtm

I think it's not a good idea to implement it.
