### ISSUE TITLE
Draw on video not work appropriately

### ISSUE THREAD

**Issue by All4Gis** [All4Gis/QGISFMV#23]
the transformation is not performed correctly on the edges of the video.
On the other hand, clicks are not drawn below the cursor

**Comment by ltbam** [comment]
I need to have a look

**Comment by ltbam** [comment]
do you have any example for this please?

**Comment by All4Gis** [comment]
later I upload a gif!no wories

**Comment by All4Gis** [comment]
but is simple,if you are drawing points on video and click,the point is not painted below the cursor!and not follow the correct object

**Comment by All4Gis** [comment]
in this gif we can see how the points are not painted under the cursor, and that they don't follow the correct position with the video is played.
I guess it's because of the transformation or some thing like that
![test_fmv2](https://user-images.githubusercontent.com/8123225/45772931-47522380-bc49-11e8-9354-a6fa63430204.gif)

**Comment by ltbam** [comment]
Ok finally that was the GetPointCommonCoords funtion in QgsVideo that was making a problem.
The coordinates rounding was too low (4 digits). I fixed to 5 digits and all is fine now.
Longitude = float(round(projPt[1], 5))
Latitude = float(round(projPt[0], 5))

fixed in the last PR
