### ISSUE TITLE
buffer metadata callbak

### ISSUE THREAD

**Issue by All4Gis** [All4Gis/QGISFMV#24]
Metadata callback run always in bakground!

for check is simple,not delete the layer when close dialog and we see how the layers continue to be updated

**Comment by ltbam** [comment]
I can't reproduce this behaviour, what I do is:

- I commented out RemoveVideoLayers() in the close event.
- I play the video and close the dialog

The layers are still there but there is nothing moving.

How can I reproduce this bug?

**Comment by All4Gis** [comment]
hmmm...is so strange then,because the steps are those!
I try it again later

**Comment by All4Gis** [comment]
I'm testing master branch. Attach a gif (QGIS 3.2)
![test_fmv2](https://user-images.githubusercontent.com/8123225/45173287-064d1e80-b208-11e8-92dd-53f72059eaad.gif)

**Comment by ltbam** [comment]
Ok I can reproduce it now.

I've seen the video is still playing after the player is closed. I've fixed that on the close event (QgisFmvPlayer) by adding a self.stop(). That worked.

**Comment by ltbam** [comment]
Test please I've fixed that in last PR

**Comment by All4Gis** [comment]
fixed #35
