### ISSUE TITLE
RTP Streaming

### ISSUE THREAD

**Issue by ltbam** [All4Gis/QGISFMV#27]
enable RTP streaming functionality

**Comment by ltbam** [comment]
A first intent for RTP Streaming has been done. I've been able to display audio and video, but still meta are missing. As we use different clients for video+audio (QMediaPlayer) and Metadata (FFMPEG) we also need to steam on different ports, because only one client can listen to one port at a time.

You can setup a RPT stream by using FFMpeg like this:
video + audio:
ffmpeg -re -i "C:\temp\movie.ts" -vcodec copy -acodec copy -f rtp_mpegts "rtp://127.0.0.1:8888" -map 0.0 -map 0.1

metadata:
ffmpeg -re -i "C:\temp\uav\movie.ts" -f rtp_mpegts "rtp://127.0.0.1:8889" -map 0.2

Problem here is that Metadata reading over RPT is quite slow.

I also tried udp streaming but QMediaPlayer says "Protocol Unknown"

You can setup a UDP stream by using FFMpeg like this:
ffmpeg -re -i "C:\temp\movie.ts" -vcodec copy -acodec copy -f mpegts "udp://127.0.0.1:8888" -map 0.0 -map 0.1

metadata:
ffmpeg -re -i "C:\temp\uav\movie.ts" -f mpegts "udp://127.0.0.1:8889" -map 0.2

**Comment by All4Gis** [comment]
RTP not show video!Can you show me a steps for reproduce it using VLC for example

**Comment by All4Gis** [comment]
work!but need reimplemet a lot of features,metadata read,draw on video etc etc.

Good Job
