### ISSUE TITLE
[FEATURE] Video manager -> Playlist

### ISSUE THREAD

**Issue by ltbam** [All4Gis/QGISFMV#39]
In some case a video is split in several mpeg or ts files. So it is interesting that the video manager can behave like a playlist and play videos seamlessly one after one.

It can be as simple as an "autoplay" toggle button in the video manager.

**Comment by All4Gis** [comment]
Is there any news on this ticket?

**Comment by All4Gis** [comment]
This ticket's been open a long time. I'm closing it for a lack of feeback.
