### ISSUE TITLE
Buffer size crash

### ISSUE THREAD

**Issue by All4Gis** [All4Gis/QGISFMV#44]
Buffer size not work in large videos.

For reproduce it:
Open a video
advance 1 or 2 minutes using the slider

And the metadata not show,the buffer has not arrived yet I think.

Use this video for test DJI_0047_MISB_F.mp4 (sample folder)

**Comment by ltbam** [comment]
Corrected here

https://github.com/All4Gis/QGISFMV/compare/md_reader_update
