### ISSUE TITLE
Crash on QGIS 3.8.1, Linux Mint

### ISSUE THREAD

**Issue by DrArn** [All4Gis/QGISFMV#62]
Hi,
This may be related to https://github.com/All4Gis/QGISFMV/issues/19#issue-348750545.
I tried all possible way of installing the plugin: From the manager and via the folders.
With and without installing the dependencies first. Only the first time when I installed from the manager I was asked for my password, but nevertheless every time I try to load the plugin QGIS crashes. I have even reinstalled QGIS completely, but it did not help.
When I start qgis from the terminal an than load the plugin this happens:
`➜  ~ qgis
lav filters
QGIS died on signal 11Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Vorgang nicht zulässig.
No thread selected
No stack.
gdb returned 0
[1]    17637 abort      qgis
`

I have no idea how to troubleshoot this and would be thankful for any help.

**Comment by All4Gis** [comment]
The problem is that I use windows!I need people for test and dev on linux

For linux you must install these packages https://github.com/All4Gis/QGISFMV/blob/master/code/utils/QgsFmvInstaller.py#L178

Need :

'sudo apt-get -y install gst123 libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio'

,FFMPEG and python requirements but when i make test OpenCV kill QGIS on ubuntu 19.04 disco.

If you open qgis without plugins it works for you, right?

look at this QGIS issue https://issues.qgis.org/issues/20837

**Comment by DrArn** [comment]
I already had these installed.

> ,FFMPEG and python requirements but when i make test OpenCV kill QGIS on ubuntu 19.04 disco.
I don't really get what your are sayi

**Comment by All4Gis** [comment]
If on windows it shouldn't fail.
That error in linux, sincerely it has not happened to me.

What I mean, I haven't managed to work in Linux. Opencv closes me QGIS without any message,So I couldn't use it on linux.

**Comment by DrArn** [comment]
So we basically have the same problem.
Is it possible/feasible to remove some functions of the plugin for testing purposes?
I also remembered that after my first install of the plugin I could load the plugin without crashing but could not use it due to opencv missing.

**Comment by All4Gis** [comment]
Yes of course. You can create a branch and modify everything you want for testing.
Maybe remove "linux installation" and what you need

**Comment by kikislater** [comment]
It doesn't crash on mine ! 
Archlinux install

**Comment by DrArn** [comment]
@All4Gis I will try as soon as I have a bit more time and understand a little more about qgis plugins and python in general.
@kikislater which QGIS do you use? And did you try to play the sample dataset?

**Comment by kikislater** [comment]
qgis 3.8. Where is the sample dataset ?

**Comment by DrArn** [comment]
@kikislater you can download it here: https://drive.google.com/drive/folders/1-B2uaW7_cfYZohZYFozrgBhIaztI1MSP

**Comment by kikislater** [comment]
It works ! But don't have this area in DTM

**Comment by kikislater** [comment]
![image](https://user-images.githubusercontent.com/13238064/62221275-7802fd80-b3c2-11e9-9e47-d7957faf81e7.png)

**Comment by kikislater** [comment]
$ pacman -Q ffmpeg
ffmpeg 1:4.1.4-1
$ which ffmpeg
/usr/bin/ffmpeg

settings.ini :
#ffmpeg path
ffmpeg : /usr/bin/

**Comment by DrArn** [comment]
@kikislater I think the plugin has a dem included. At least the installer references a "DEM-Mundial.rar".
Maybe I should try an downgrade since I am using QGIS 3.8.1-Zanzibar.
I just now noticed the same problem when installing an other plugin: https://github.com/KIOS-Research/ImportPhotos
This one worked before.

**Comment by All4Gis** [comment]
> It doesn't crash on mine !
> Archlinux install
> 
> But I don't use the plugin ... Still don't understand which kind of video is needed even if some references are precised : STANAG_4609_Ed3, ST0601.13, ST0902.1 ... Still confused for me, so it's installed on my qgis but never used it

check this site about stanag https://impleotv.com/2017/02/17/klv-encoded-metadata-in-stanag-4609-streams/

**Comment by All4Gis** [comment]
> @kikislater I think the plugin has a dem included. At least the installer references a "DEM-Mundial.rar".
> Maybe I should try an downgrade since I am using QGIS 3.8.1-Zanzibar.
> I just now noticed the same problem when installing an other plugin: https://github.com/KIOS-Research/ImportPhotos
> This one worked before, now the installation does not even finish.

Nope, you need put your DTM path in [settings.ini](https://github.com/All4Gis/QGISFMV/blob/master/code/settings.ini#L3) this current path is a sample,because this tif is in my laptod

**Comment by All4Gis** [comment]
The dev branch is working for me in ubuntu 18.04!check it

**Comment by All4Gis** [comment]
Closed for lack of feedback

**Comment by dima-covar** [comment]
I'm having similar issues on Ubuntu 18.04, QGIS 3.14. I followed all of the instructions as far as I can tell. Seeing this when I activate the plugin:

```
lav filters
QGIS died on signal 11Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No thread selected
No stack.
gdb returned 0
Aborted (core dumped)
```

I tried to install QGIS 3.8, but none of the instructions I've tried have worked for me yet.  @All4Gis , could you potentially verify that this also works for QGIS 3.14? 

Thanks for the good work :)

**Comment by All4Gis** [comment]
In ubuntu it should work. I'll have to check again with QGIS 3.14
