### ISSUE TITLE
Start Location not available // Not MISB

### ISSUE THREAD

**Issue by WBOA** [All4Gis/QGISFMV#66]
Hello,
Thanks in advance for your answers:
under win10 64b using Qgis3.4.9 LTR.
Plugin show (finaly) no message, Installation of dependencies show no erreur.
However i still get "not Misb" in status and "Start location not available" when opening uploded files that assumed to be MSIB compliant.

Any ideas ?
Regards
![SShot](https://user-images.githubusercontent.com/23560922/64853903-ba079c00-d61c-11e9-983f-e402616659c0.jpg)

**Comment by All4Gis** [comment]
Hi!Probably you dont have correct FFMPEG path in setting.ini file! check this path

**Comment by WBOA** [comment]
Hello,
Thanks for your answer. That was my first thougth but if I change the ffmpeg path into the settings.ini to c:/somewrongpath/  i get an warning popup message at QGIS lauching (cf. picture).
Otherwise if i have what i think is the right path i get no warning.
Do you have an other guess?
thanks
![1](https://user-images.githubusercontent.com/23560922/64945720-7fe30800-d871-11e9-9350-024a22ca9a4d.jpg)

**Comment by All4Gis** [comment]
mm..Doesn't work with example videos? for example with cheyenne.ts

**Comment by WBOA** [comment]
Unfortunlatky not.
Il "load" the file to 99% and stays on "not MISB" and "Start location not available"
Just tolet you know I tried both 64b and 32b version of ffmpeg. Currently back to 64b version.
![2](https://user-images.githubusercontent.com/23560922/64946584-7eb2da80-d873-11e9-8d29-e0805901d7ae.jpg)

**Comment by All4Gis** [comment]
What plugin version are you using?Can you try using the master branch?

**Comment by WBOA** [comment]
I used the 1.7. on QGIS3.4.9 LTR
I will try the master branch but it said to work only on 3.8// 3.99.
I m going to install last version of qgis an test again. I let you know.
Thanks a lot

**Comment by WBOA** [comment]
Ok
![3](https://user-images.githubusercontent.com/23560922/64951004-18cb5080-d87d-11e9-9cd4-100750566597.jpg)
 it work on qgis 3.8 with the master branch version.
But now as it open the Player interface and load the differents layer, i can t play the video.

**Comment by All4Gis** [comment]
If you cann't reproduce it is because you must miss install LAV Filters! https://github.com/All4Gis/QGISFMV#for-show-video

**Comment by WBOA** [comment]
A big thanks it works and it is amazing! you did a awesome job here!
Next step making my own MISB from underwater and DJI.
Regards

**Comment by All4Gis** [comment]
thanks!I'm glad it works for you.
