### ISSUE TITLE
Please remove binary files

### ISSUE THREAD

**Issue by pcav** [All4Gis/QGISFMV#7]
In particular docx. Please use the standard doc system for QGIS, based on rst and sphinx.
Thanks.

**Comment by All4Gis** [comment]
Okey!thanks

**Comment by pcav** [comment]
docx should not be in the repo altogether.
thanks.

**Comment by All4Gis** [comment]
thanks for your suggestion! The corresponding uploaded zip has no docx.
Do you accept the upload of the plugin or not?
In the future I will change that extension for another in this project
thanks

**Comment by pcav** [comment]
Unfortunately this is not possible. The content of th ofe zip should be exactly that of the repo.
Thanks.

**Comment by All4Gis** [comment]
okey not problem! upload again!
but i have a question!
since when it has to be equal a plugin uploaded to qgis and the development in github! it's stupid

**Comment by pcav** [comment]
Difficult that something designed by some of the best developer around, and used by hundreds of clever people, would be stupid. Please check again.

**Comment by All4Gis** [comment]
the upload zip in qgis plugins repository is exactly the same that [https://github.com/All4Gis/QGISFMV/releases/tag/v1.1](link), but no worries and generate new release and remove the zip from qgis page

**Comment by All4Gis** [comment]
Upload again without binary files this github tag [https://github.com/All4Gis/QGISFMV/releases/tag/v1.1](1.1)

**Comment by All4Gis** [comment]
thank for approval!Close this
