### ISSUE TITLE
FFMPEG download failed

### ISSUE THREAD

**Issue by akunnyapeta** [All4Gis/QGISFMV#70]
'Missing dependency, Do you want install FFMPEG?'
I clicked yes, but the download no respond. Using QGIS 3.10.3 Windows 10.

**Comment by kcramos19** [comment]
I have same issue too. Thank you so much

**Comment by kcramos19** [comment]
if buttonReply == QMessageBox.Yes:
            # Download FFMPEG # Prevent HTTP Error 403: Forbidden
            progressMessageBar = iface.messageBar().createMessage("QGIS FMV", " Downloading FFMPEG...")
            progressMessageBar.layout().addWidget(progress)
            iface.messageBar().pushWidget(progressMessageBar, QGis.Info)

Error in download. please help. Thank you in advance

**Comment by MaxHouel** [comment]
If you download directly FFMPEG on the official website. Change the name of the folder, and place it in root like : "C:\FFMPEG". Then I noticed that the folder downloaded on the website organize the folder like this : C:\FFMPEG\bin\ .exe file, so you should move all the file of the bin folder in the previous one. For me it work by following all the instruction on the video. Hope it help.

**Comment by kcramos19** [comment]
Hi, I already solve the problem regarding in FFMPEG but now if I double
click the uploaded video file no video player come out. any idea how to fix
this? Thank you in advance

**Comment by akunnyapeta** [comment]
> If you download directly FFMPEG on the official website. Change the name of the folder, and place it in root like : "C:\FFMPEG". Then I noticed that the folder downloaded on the website organize the folder like this : C:\FFMPEG\bin\ .exe file, so you should move all the file of the bin folder in the previous one. For me it work by following all the instruction on the video. Hope it help.

I solved the problem, Thank you so much

**Comment by kcramos19** [comment]
Solved. Thank you so much

**Comment by All4Gis** [comment]
I reopen this issue, because is a bug.
