### ISSUE TITLE
[BUG] Index Error: Invalid start byte

### ISSUE THREAD

**Issue by martyrocks** [All4Gis/QGISFMV#79]
**Describe the bug**
Error message when I click on 'extract recording' from the MISB Creator tool:
An error has occurred while executing Python code: 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 7464: invalid start byte 
Traceback (most recent call last):
  File "C:/Users/mrocks/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\manager\QgsMultiplexor.py", line 218, in CreateCSV
    self.ReadCSVRecordings(input_metadata)
  File "C:/Users/mrocks/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\manager\QgsMultiplexor.py", line 577, in ReadCSVRecordings
    for row in reader:
  File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\csv.py", line 112, in __next__
    row = next(self.reader)
  File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 7464: invalid start byte

**Desktop (please complete the following information):**
 - OS: - Windows 10
 - QGIS Version - 3.4.0
 - Plugin Version - 1.9.0 )I think)

**Additional context**
Video and data file extracted from Mavic Phantom Pro. I've attached the original 

.txt file, and the converted .csv file (converted using 'CsvView'.
[DJIFlightRecord_2019-10-21_[14-01-53].txt](https://github.com/All4Gis/QGISFMV/files/4688221/DJIFlightRecord_2019-10-21_.14-01-53.txt)
[Oct-21st-2019-02-01PM-Flight-Airdata1111111.zip](https://github.com/All4Gis/QGISFMV/files/4688223/Oct-21st-2019-02-01PM-Flight-Airdata1111111.zip)

Any assistance would be fantastic, my python knowledge is extremely limited I'm afraid. 

Marty

**Comment by All4Gis** [comment]
Thanks for the feedback. ASAP I'll fixed

**Comment by martyrocks** [comment]
> Thanks for the feedback. ASAP I'll fixed

Sweet, cheers! Great plugin by the way, really keen to try it out as soon as possible!

**Comment by All4Gis** [comment]
The attached csv works without problems from my side
