### ISSUE TITLE
[BUG] Frame capture tools returns a blank image

### ISSUE THREAD

**Issue by emiliobruno** [All4Gis/QGISFMV#82]
**Describe the bug**
All capture frame tools returns a blank image, except the mosaic tool, with or without draws,pausing or running the videos.
Even the metadata pdf report returns a blank image.Tested with all sample videos.
[Cheynne_frame_report.pdf](https://github.com/All4Gis/QGISFMV/files/4775805/Cheynne_frame_report.pdf)

Thanks, 
EB

**Comment by All4Gis** [comment]
Does the mosaic tool work? Strange. You have opencv installed, right?

**Comment by emiliobruno** [comment]
Hello, 
Ubuntu version : 
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
kernel : 5.4.0-37-generic

QGIS:
![image](https://user-images.githubusercontent.com/6531323/84605783-6f020a00-ae76-11ea-8ba6-940e98d0c972.png)
I have checked the file QgsFvmPlayer.py that the function 
 def SaveAllFrames(self, task, fileName, directory):
        ''' Extract and save all video frames into directory '''
        vidcap = cv2.VideoCapture(fileName)
uses cv2 . 
This funcion is working perfectly

The function 
    def ExtractCurrentFrame(self):
        """ Extract Current Frame Task
            The drawings are saved by default
        """
        # image = self.videoWidget.currentFrame()   # without drawings
        image = BurnDrawingsImage(self.videoWidget.currentFrame(), self.videoWidget.grab(self.videoWidget.surface.videoRect()).toImage())

uses BurnDrawingsImage in file QgsFmvUtils.py function that uses 
 p = QPainter()
    p.setRenderHint(QPainter.HighQualityAntialiasing)
    p.begin(base)
    p.setCompositionMode(QPainter.CompositionMode_SourceOut)
    p.drawImage(0, 0, overlay)
    p.end()
not cv2.
I hope helped you to help me.
Thanks
EB

**Comment by emiliobruno** [comment]
Any opinion ?

**Comment by All4Gis** [comment]
I'm sorry, but I don't have time right now. When I can look at this.
