### ISSUE TITLE
[FEATURE] Process frames, process the frames and extracting meta data

### ISSUE THREAD

**Issue by ramdhan1989** [All4Gis/QGISFMV#83]
I have .ts file recorded by drone. I would like to run my python script for object detection for each frame in the .ts video file. Currently, I am using opencv capture to read the frames. cv2.cv.CV_CAP_PROP_FRAME_COUNT returns 37082302. meanwhile, it only around 5000 frames in the end of looping. There must be other data in .ts file since the difference is huge (37082302 vs 5000 frames). I need to detect object as well as get the meta data associated with each frame. I wonder if this package could help my problem ? 

thank you

**Comment by All4Gis** [comment]
Yes, but you would have to implement automatic object detection. Right now only the object tracking is implemented based on an area selected by the user

**Comment by ramdhan1989** [comment]
what do you mean by automatic object detection ? currently I am using darknet yolo and open cv to do that.
I just want to get this information from .ts file but I couldn't get it. I believe they are stored in .ts file. I can see it using impleoTV software.
![image](https://user-images.githubusercontent.com/41245856/84994426-dec50d00-b174-11ea-8c82-d6a3a9f50cfa.png)

Thank you

**Comment by All4Gis** [comment]
I misunderstood you then., but Yes yes, it is implemented here, you just have to open the metadata window to see the telemetry of each frame and you can save it in a pdf format or csv format

**Comment by ramdhan1989** [comment]
is it possible to extract automaticaly for all frames into one csv file ?

**Comment by All4Gis** [comment]
Possible but not implemented

**Comment by ramdhan1989** [comment]
What is modul or function that used to extract metadata in your repository?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by All4Gis** [comment]
https://github.com/All4Gis/QGISFMV/tree/master/code/klvdata

**Comment by ramdhan1989** [comment]
Thank you very much

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
