### ISSUE TITLE
[BUG] Opencv error descarga github

### ISSUE THREAD

**Issue by jcfuragaro** [All4Gis/QGISFMV#84]
**Describe the bug**
Al instalar Opencv desde:
https://github.com/All4Gis/QGISFMV/blob/master/code/install-opencv.sh

No logra hacer la descarga en la solicitud "wget https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip" 
presenta el mensaje:
--2020-06-21 12:00:56--  https://github.com/opencv/opencv/archive/.zip
Resolviendo github.com (github.com)... 140.82.113.3
Conectando con github.com (github.com)[140.82.113.3]:443... conectado.
Petición HTTP enviada, esperando respuesta... 404 Not Found
2020-06-21 12:00:57 ERROR 404: Not Found.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - QGIS Version [3.14.0]
 - Plugin Version [ 1.9.0]

**Additional context**

**Comment by All4Gis** [comment]
esto esta probado con ubuntu 18.04 puede que por algún motivo no te resulva la versión de opencv pero bueno puedes probar modificando ese .sh y poniendo la versión a mano,sin usar la variable

**Comment by All4Gis** [comment]
utiliza este script oara ubuntu 20.la version de opencv puedes cambiarla pero creo que aunque sea superior el plugin funcionará


https://raw.githubusercontent.com/milq/milq/master/scripts/bash/install-opencv.sh

**Comment by jcfuragaro** [comment]
Listo, Ya lo instalé y ya no aparece ninguna advertencia.
