### ISSUE TITLE
[BUG] Al crear el MISB con datos de vuelo de la aplicación Litchi

### ISSUE THREAD

**Issue by jcfuragaro** [All4Gis/QGISFMV#86]
**Describe the bug**
Hola @FranRaga, he estado usando FMV con el Flight record de DJI GO 4, paso el txt por (https://www.phantomhelp.com/LogViewer/Upload/)  y descargo el  CSV “Download Verbose CSV” con el cual creo el “Archivo MISB” y funciona a la perfección. Ahora bien, en estos momentos volé con litchi el cual ya viene en CSV que lo descargo directamente de (https://airdata.com/) y trato de crear el MISB y me arroya un error. Lo paso por (https://www.phantomhelp.com/LogViewer/Upload/) y descargo el CSV e igual sale un error. 
Saludos

**To Reproduce**
(1) Al descargar el csv [1] que es sincronizado a https://airdata.com/ desde el apps de litchi que está  instalado en el ipad/iphone, en FMV al tratar de crear el MISB aparece el siguiente error:
Traceback (most recent call last):
  File "/home/geo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QGIS_FMV/manager/QgsMultiplexor.py", line 222, in CreateCSV
    self.ReadCSVRecordings(input_metadata)
  File "/home/geo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QGIS_FMV/manager/QgsMultiplexor.py", line 606, in ReadCSVRecordings
    self.CreateDJICsv(rows_list, csv_raw)
  File "/home/geo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QGIS_FMV/manager/QgsMultiplexor.py", line 633, in CreateDJICsv
    csv.writer(f_output).writerows(itertools.islice(csv_input, int(values[0]), int(values[-1])))
IndexError: list index out of range
Versión de Python: 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0] 
Versión de QGIS: 3.14.0-Pi Pi, 9f7028fd23 
[1]https://drive.google.com/file/d/1KgiMvKAydirpxiytNcXmMVdgJafdYORU/view?usp=sharing

(2) el archivo [1] se sube a https://www.phantomhelp.com/LogViewer/Upload/ donde posteriormente es descargado [2] aparece el mismo error.
[2] https://drive.google.com/file/d/1MqG5SxVpoGLF0ux1Zd52SljhP1B9I7I9/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - QGIS Version [e.g. 3.14.0]
 - Plugin Version [e.g. 1.9.0]

**Additional context**
El error lo tengo es con los datos del apps litchi, con DJI GO 4 no se presenta el inconveniente.

**Comment by All4Gis** [comment]
buenas

el csv tiene que tener un formato en concreto,puedes comparar los dos csv y morar si las cabeceras son las mismas(mismo nombre y mismo nombre). si no lo son no va a funcionar y tendria que implementarse un parser para esa estructura en concreto

**Comment by jcfuragaro** [comment]
Consulta, FMV usa todos los campos del metadato de vuelo?
He visto que en "QgsMultiplexor.py" sólo aparecen estos datos:

CUSTOM.updateTime
OSD.yaw
OSD.pitch
OSD.roll
OSD.latitude
OSD.longitude
OSD.altitude [m]
OSD.height [m]
GIMBAL.yaw
GIMBAL.pitch
GIMBAL.roll

Saludos

**Comment by All4Gis** [comment]
Si, efectivamente solo se usan esos, pero ten en cuenta que si solo dejas esos campos luego los metadatos que te saldran en el panel del plugin solo seran esos tambien.

**Comment by jcfuragaro** [comment]
Hola Fran!
Al dejar el mismo orden de los campos y sólo la información [1] que necesita FMV aún me sale el mismo error, podrías darle una mirada al archivo por favor? por ahora lo único que necesito es que siga el  recorrido y muestre la ubicación del drone en QGIS.
Mil gracias


[1] https://drive.google.com/file/d/1aYAcvCOJqhcBuMPvGLA_M5bay_9ESA31/view?usp=sharing

**Comment by jcfuragaro** [comment]
Hola Fran!
Al dejar el mismo orden de los campos y sólo la información [1] que necesita FMV aún me sale el mismo error, podrías darle una mirada al archivo por favor? por ahora lo único que necesito es que siga el  recorrido y muestre la ubicación del drone en QGIS.
Mil gracias


[1] https://drive.google.com/file/d/1aYAcvCOJqhcBuMPvGLA_M5bay_9ESA31/view?usp=sharing
