### ISSUE TITLE
[FEATURE]  Is there a way to use GoPro videos with QGIS FMV?

### ISSUE THREAD

**Issue by stefan-overkamp** [All4Gis/QGISFMV#87]
How to make the video MISB conform with the gopro metadata?

**Comment by All4Gis** [comment]
You would have to implement the parser for that csv or put the csv headers as needed in the https://github.com/All4Gis/QGISFMV/blob/master/code/manager/QgsMultiplexor.py#L234

**Comment by stefan-overkamp** [comment]
Ok, thanks. I tried with a csv (headers as needed) but get:
 Video info callback failed! : : [Errno 2] No such file or directory: 'C:\\Users\\stefan\\QGIS_FMV\\GH010425\\klv\\0.0.klv'

**Comment by All4Gis** [comment]
I'd have to see if I had a csv file in order to reproduce it. You may have to make more changes

**Comment by stefan-overkamp** [comment]
This is the one I use for testing
[metadata_korr.zip](https://github.com/All4Gis/QGISFMV/files/4953836/metadata_korr.zip)

**Comment by stefan-overkamp** [comment]
I succeeded in calculating a csv file that can be used with Video Multiplexor.
[GX010488.zip](https://github.com/All4Gis/QGISFMV/files/5252125/GX010488.zip)

There are still configuration issues, as GoPro Video taken by bikes are different to drone videos.

**Comment by guyanf** [comment]
@stefan-overkamp Could you add the GoPro videos(taken by car or bike) with FMV?
Now, I have the similar question.
I want to add the insta360 video with FMV.
Thanks a lot!

**Comment by stefan-overkamp** [comment]
@guyanf Sorry for the delay. I will try to upload a small video sequence next week. I think a full video will reach the size limit.

**Comment by stefan-overkamp** [comment]
@guyanf At following link you can find part of a GoPro8 video and metadata.csv for QGIS FMV:
https://geodaten-velbert.de/nextcloud/s/ZMQwCH6i9RFNWLL

**Comment by All4Gis** [comment]
thanks, Can I add it to the public video repository?

**Comment by stefan-overkamp** [comment]
I would like to create another extract without any car plates visible but was not able to generate a metadata.csv from the ffmpeg processed file. so maybe problematic.

**Comment by thbaumann** [comment]
@stefan-overkamp : Is the testvideo+csv still downloadable somewhere? the nexcloud link is password-protected.

I am also interested in having a testcase to show gopro videos inside QGIS. 
What were theconfiguration issues you had? ("There are still configuration issues, as GoPro Video taken by bikes are different to drone videos.")

**Comment by stefan-overkamp** [comment]
@thbaumann Sorry, there are license plates in the video stream and privacy issues. Hope to get a free video in next few weeks.

**Comment by sabinkolarov** [comment]
Here is a video from GoPro8 if it will be helpful. the video can be used freely, no personal data.
https://e.pcloud.link/publink/show?code=kZwQVVZvrMrAzk7dbyT6udRTNQ0OVDeRUjy
