### ISSUE TITLE
[BUG]: QGIS Crashes when installing FMV plugin

### ISSUE THREAD

**Issue by vlsalsa** [All4Gis/QGISFMV#89]
**Describe the bug**
Under Ubuntu, QGIS crashes when I attempt to install the QGIS FMV plugin. 

**To Reproduce**
1. Go to QGIS
2. Click on plugins
3. Scroll down to install plugin. 
4. QGOS Crashes
5. Open relaunching it appears the plugin is installed, but I am unable to select it, when I do, QGIS crashes. 

**Expected behavior**
I expected to be able to click on the plugin and open the videos as shown. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - QGIS Version 3.14
 - Plugin Version 1.9

**Additional context**

**Comment by All4Gis** [comment]
HI, can you try with the manual installation please? https://github.com/All4Gis/QGISFMV#installation-on-ubuntu

**Comment by vlsalsa** [comment]
I will try running those again with QGis open and then close at the appropriate time. 

Another issue: when I run "sh install-opencv.sh"

I get the following error:
install-opencv.sh: 7: install-opencv.sh: Syntax error: newline unexpected

**Comment by vlsalsa** [comment]
so I uninstalled everything, reinstalled using those instructions on Ubuntu, and the plugin did not show up in QGis. 

I tried installing the plugin from the list and crashed again. 

Of note: I can not find the "settings.ini" file you mention in the pre-requisites section.

**Comment by vlsalsa** [comment]
More information:

**Comment by All4Gis** [comment]
any update @vlsalsa ?
